---
title: "TP1"
author: "Mame Libasse Mboup"
date: "20/09/2021"
output: pdf_document
---

# PARALLEL COMPUTING FOR DATA SCIENCE
## Lab x001 : Warm-up

### Exercice 1 : Calcul avec virgule flottante ####

```{r}
is.integer(2)
if(sqrt(2) * sqrt(2) != 2) print("what ?!")
if(0.1 + 0.2 == 0.3) print("result is ok")
if(0.1 + 0.2 != 0.3) print("no way !!!!")
```

### Exercice 2 : Optimisation numérique ####

```{r}
#1.

f <- function(x){
   a <- sin(x)^2
   b <- sqrt(abs(x-3))
   r <- a + b
   r
}


#2.Courbe de la fonction f sur [-6,4]
curve(f, from = -6, to = 4, lwd =2)

#3.
integrate(f, -6, 4)

#4.
mn <- optimize(f, interval = c(-6,4))
mn

mx <- optimize(f, interval = c(-6,4), maximum= TRUE)
mx

abline(h = mn$objective, col ="blue")
abline(h = mx$objective, col ="red")

```

### Exercice 3 : Problème ####

```{r}
rm(list = ls())
#1. 
#rnorm genere des nombres aléatoires à partir de la distribution normale
simuData <- function(n){
  rnorm(n)
}
x <- simuData(20)
x

#2.
perteprim <- function(s,y, p){
  
  for(i in 1:length(y)){
      x = x + ( abs(s-y[i]) ^ p ) 
  }
  
  res = x ^ (1/p)
  res
}

perte <- function(s,y, p){
  return ( sum(abs(s-y) ^ p ) ^ (1/p))
}

#3.
for ( p in c(1,2,5,1/2) ){
  print(paste("Pour p = ", p))
  min <- optimize(perte, interval = range(x), y = simuData(20), p=p)
  print(min)
}

#4.
curve(perte( simuData(20) ) ,from = -10, to = 10) 

```

